/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View_Template;

import View_Template.*;
import DomainModels.Model_Menu;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.JFrame;

/**
 *
 * @author asus
 */
public class JPanel_Menu extends javax.swing.JPanel {

    public event.EventMenuSelected event;
    public void addEventMenuSelected(event.EventMenuSelected event){
        this.event = event;
        listMenu1.addEventMenuSelected(event);
    }
    
    
    public JPanel_Menu() {
        initComponents();
        setOpaque(false);
        listMenu1.setOpaque(false);
        init();
    }
    private void init(){
        listMenu1.addItems(new Model_Menu("house","Trang Chủ",Model_Menu.MenuType.MENU));
        listMenu1.addItems(new Model_Menu("","",Model_Menu.MenuType.SPACE));
        listMenu1.addItems(new Model_Menu("cart","Bán Hàng",Model_Menu.MenuType.MENU));
        listMenu1.addItems(new Model_Menu("","",Model_Menu.MenuType.SPACE));
        listMenu1.addItems(new Model_Menu("product","Sản Phẩm",Model_Menu.MenuType.MENU));
        listMenu1.addItems(new Model_Menu("","",Model_Menu.MenuType.SPACE));
        listMenu1.addItems(new Model_Menu("employee","Nhân Viên",Model_Menu.MenuType.MENU));
        listMenu1.addItems(new Model_Menu("","",Model_Menu.MenuType.SPACE));
        listMenu1.addItems(new Model_Menu("traveler","Khách Hàng",Model_Menu.MenuType.MENU));
        listMenu1.addItems(new Model_Menu("","",Model_Menu.MenuType.SPACE));
        listMenu1.addItems(new Model_Menu("bill","Hóa Đơn",Model_Menu.MenuType.MENU));
        listMenu1.addItems(new Model_Menu("","",Model_Menu.MenuType.SPACE));
        listMenu1.addItems(new Model_Menu("analytics","Thống Kê",Model_Menu.MenuType.MENU));
        
        listMenu1.addItems(new Model_Menu("","",Model_Menu.MenuType.SPACE));
        listMenu1.addItems(new Model_Menu("check-out","Đăng Xuất",Model_Menu.MenuType.MENU));
    
    
    }

    @Override
    protected void paintChildren(Graphics g) {
        Graphics2D g2 = (Graphics2D) g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint g1 = new GradientPaint(0, 0, Color.decode("#1CB5E0"), 0, getHeight(), Color.decode("#000046"));
        g2.setPaint(g1);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        g2.fillRect(getWidth() - 20, 0, getWidth(), getHeight());
        super.paintChildren(g); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }
    
    private  int x;
    private  int y;
    
    public  void initMoving(JFrame jFrame){
        jPanel_logo.addMouseListener(new MouseAdapter(){
            @Override
            public void mousePressed(MouseEvent e) {
                   x = e.getX();
                   y = e.getY();
            }
            
        });
        jPanel_logo.addMouseMotionListener(new MouseMotionAdapter(){
            @Override
            public void mouseDragged(MouseEvent e) {
                jFrame.setLocation(e.getXOnScreen() - x, e.getYOnScreen() - y);
            }
            
        });
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_logo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        listMenu1 = new DomainModels.ListMenu<>();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(215, 454));

        jPanel_logo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel_logo.setOpaque(false);

        jLabel1.setText("CHU VAN TRAM");

        javax.swing.GroupLayout jPanel_logoLayout = new javax.swing.GroupLayout(jPanel_logo);
        jPanel_logo.setLayout(jPanel_logoLayout);
        jPanel_logoLayout.setHorizontalGroup(
            jPanel_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_logoLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel1)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel_logoLayout.setVerticalGroup(
            jPanel_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_logoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(listMenu1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel_logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(listMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel_logo;
    private DomainModels.ListMenu<String> listMenu1;
    // End of variables declaration//GEN-END:variables
}
